concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "_GITLAB_HOST_"
  url = "http://_GITLAB_HOST_/"
  token = "_TOKEN_"
  executor = "shell"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
